// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestWindSystemLibrary
{
    public partial class PaymentType
    {
        public PaymentType()
        {
            Payments = new HashSet<Payment>();
        }

        [Key]
        public byte PaymentTypeID { get; set; }
        [Required]
        [StringLength(40)]
        [Unicode(false)]
        public string PaymentTypeDescription { get; set; }

        [InverseProperty(nameof(Payment.PaymentType))]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}